apiVersion: v1
kind: ConfigMap
metadata:
  name: core3api
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "System": "Error",
          "Microsoft": "Error"
        }
      },
      "message": {
        "text": "Lorem Ipsum is simply dummy text of the printing and typesetting prd."
      }
    }